/** Named vec4 rows of the shared ABI display-list record. */
export const fields = {
  bounds: 0,
  cornerRadius: 1,
  color: 2,
  color2: 3,
  border: 4,
  borderColor: 5,
  shadow: 6,
  shadowColor: 7,
  clipBounds: 8,
  clipRadius: 9,
  gradient: 10,
  typeInfo: 11,
  cornerShape: 12,
  via: 13,
  stops: 14,
  affine: 15,
  borderTop: 16,
  borderRight: 17,
  borderBottom: 18,
  borderLeft: 19,
  fadeBounds: 20,
  fade: 21,
  shapeFrame: 22,
  shapeRest: 23,
  shape: 24,
  notchCorners: 25,
  notchTop: 26,
  notchBottom: 27,
} as const;
